AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: <your stack description here>

Resources:
  # AppApiGateway:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: Prod
  #     DefinitionBody:
  #       swagger: "2.0"
  #       info:
  #         title: Blinkit API
  #         version: "1.0"
  #       paths:
  #         /:
  #           post:
  #             x-amazon-apigateway-binary-media-types:
  #               - '*/*'
  #           consumes:
  #             - multipart/form-data
  #             - application/json
  #           responses:
  #             "200":
  #               description: "Success response"
  #           requestTemplates:
  #             multipart/form-data: |
  #               {
  #                 "body": "$input.body",
  #                 "headers": {
  #                   "Authorization": "$input.params().header.get('Authorization')"
  #                 },
  #                 "isBase64Encoded": false
  #               }
  #             application/json: |
  #                 {
  #                 "body": "$input.body",
  #                 "headers": {
  #                   "Authorization": "$input.params().header.get('Authorization')"
  #                 },
  #                 "isBase64Encoded": false
  #                 }
  #               # Replace with your JSON request template if needed
  #     BinaryMediaTypes:
  #       - "*/*"

  UserHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.user_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        UserApiEvent:
          Type: Api
          Properties:
            Path: /user
            Method: post

  AdminHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.admin_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        AdminApiEvent:
          Type: Api
          Properties:
            Path: /admin
            Method: post
  
  LoginHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.login_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        LoginApiEvent:
          Type: Api
          Properties:
            Path: /login
            Method: post

  CreateCategoryHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.category_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        CreateCategoryApiEvent:
          Type: Api
          Properties:
            Path: /admin/category
            Method: post
            # RestApiId:
            #   Ref: AppApiGateway

  CreateSubcategoryHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.subcategory_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        CreateSubcategoryApiEvent:
          Type: Api
          Properties:
            Path: /admin/subcategory
            Method: post

  CreateProductHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.product_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        CreateProductApiEvent:
          Type: Api
          Properties:
            Path: /admin/product
            Method: post

  GetCategoriesHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.get_categories_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        GetCategoriesApiEvent:
          Type: Api
          Properties:
            Path: /admin/categories
            Method: get

  UserGetCategoriesHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.user_get_categories_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        GetCategoriesApiEvent:
          Type: Api
          Properties:
            Path: /user/categories
            Method: get

  UserGetCategorySubcategoriesHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.user_get_category_subcategories_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        GetCategoriesApiEvent:
          Type: Api
          Properties:
            Path: /user/category/subcategories
            Method: post

  UserGetSubcategoryProductsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.user_get_subcategory_products_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        GetCategoriesApiEvent:
          Type: Api
          Properties:
            Path: /user/subcategory/products
            Method: post

  UserGetSpecificProductHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.user_get_specific_product_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        GetSpecificProductApiEvent:
          Type: Api
          Properties:
            Path: /user/product/{product_id}
            Method: get

  OrderHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.create_order_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        GetSpecificProductApiEvent:
          Type: Api
          Properties:
            Path: /user/order
            Method: post

  GetSubcategoriesHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.get_subcategories_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        GetSubcategoriesApiEvent:
          Type: Api
          Properties:
            Path: /admin/subcategories
            Method: get

  GetCategorySubcategoriesHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.get_category_subcategories_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        GetSubcategoriesApiEvent:
          Type: Api
          Properties:
            Path: /admin/category/subcategories
            Method: post
            

  UpdateCategoryHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.update_category_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        UpdateCategoryApiEvent:
          Type: Api
          Properties:
            Path: /admin/category
            Method: put

  UpdateSubcategoryHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.update_subcategory_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        UpdateSubcategoryApiEvent:
          Type: Api
          Properties:
            Path: /admin/subcategory
            Method: put

  GetProductsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.get_products_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        GetProductsApiEvent:
          Type: Api
          Properties:
            Path: /admin/products
            Method: get

  GetSpecificProductHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.get_specific_product_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        GetSpecificProductApiEvent:
          Type: Api
          Properties:
            Path: /admin/product/{product_id}
            Method: get

  GetSubcategoryProductsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.get_subcategory_products_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        GetSpecificProductApiEvent:
          Type: Api
          Properties:
            Path: /admin/subcategory/products
            Method: post

  UpdateProductHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.update_product_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        UpdateProductApiEvent:
          Type: Api
          Properties:
            Path: /admin/product
            Method: put

  DeleteProductHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.delete_product_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        DeleteProductApiEvent:
          Type: Api
          Properties:
            Path: /admin/product/{product_id}
            Method: delete

  DeleteCategoryHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.delete_category_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        DeleteCategoryApiEvent:
          Type: Api
          Properties:
            Path: /admin/category/{category_id}
            Method: delete

  DeleteSubcategoryHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.delete_subcategory_handler 
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        DeleteSubcategoryApiEvent:
          Type: Api
          Properties:
            Path: /admin/subcategory/{subcategory_id}
            Method: delete
  CreateCategoryUsingFormDataHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.category_form_handler
      Runtime: python3.10
      Timeout: 60
      CodeUri: ./src/
      Environment:
        Variables: 
          MONGODB_PWD: jPNxaeDm89o3eh5B
          SECRET_KEY: dc8cd8d5a584b184e99e866f6893770c
          CLOUD_NAME: ddzoadcde
          API_KEY: 399475918152762
          API_SECRET: ocy_ICUvVSeAjKV7Vh1Ba5TOi1I
      Events:
        CreateCategoryApiEvent:
          Type: Api
          Properties:
            Path: /admin/categoryForm
            Method: post
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        openapi: "3.0.0"
        info:   
          title: Blinkit API
          version: "1.0"
        paths:
          /:
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                  multipart/form-data:
                    schema:
                      type: object
                      properties:
                        file:
                          type: string
                          format: binary
              responses:
                '200':
                  description:'Success'
            # RestApiId:
            #   Ref: AppApiGateway
  